baseURL = "https://aben20807.github.io/"
languageCode = "zh-tw"
title = "記錄用"

theme = "hugOuO"
DefaultContentLanguage = "zh"
enableEmoji = true
pygmentsCodeFences = true           # for code highlighting
pygmentsStyle = "monokai"
enableInlineShortcodes = true
googleAnalytics = "UA-123296010-2"
disqusShortname = "forrecording"
enableGitInfo = true                # for last modified
footnoteAnchorPrefix = "ouo:"
footnoteReturnLinkContents = "<sup>[↩]</sup>"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Footer

[params]
author = "Huang Po-Hsuan"
classes = []

[author]
name = "Huang Po-Hsuan"
email = "aben20807@gmail.com"

# Navbar

[menu]

[[menu.social]]
name = "GitHub"
title = "fab fa-github-square"
url = "https://github.com/aben20807/blog-post"

[[menu.social]]
name = "YouTube"
title = "fab fa-youtube-square"
url = "https://www.youtube.com/channel/UCEiQdnpoVJcaca7jWlPjEdw"

[[menu.social]]
name = "Linkedin"
title = "fab fa-linkedin"
url = "https://www.linkedin.com/in/po-hsuan-huang-6587b6117/"

[[menu.main]]
weight = 2
name = "分類"
title = "分類"
url = "/categories/"

[[menu.main]]
weight = 3
name = "標籤"
title = "標籤"
url = "/tags/"

[[menu.main]]
weight = 4
name = "關於"
title = "關於"
url = "/about"

# Tools

[taxonomies]
category = "categories"
tag = "tags"

[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML", "RSS"]

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
